test

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  custom_job:
+  custom_job_1:
     runs-on: ubuntu-latest
 
     steps:
@@ -16,42 +16,27 @@ jobs:
 
       - name: Your Custom Step 1
         id: custom_step_1
-        env:
-          var: 1
         run: |
-          if [ "$var" -eq 2 ]; then
-            # Increment the variable by +1
-            var=$((var+1))
-            echo "var is equal to 1"
-            echo "::set-output name=status::pass" # Set a custom output named 'status' to 'pass'
+          # Your custom script or command here
+          # Example:
+          if [ "$SOME_CONDITION_1" != "true" ]; then
+            echo "Custom Job 1 Failed"
+            exit 1  # Set a non-zero exit status to indicate failure
           else
-            echo "var is not equal to 1, failing the job"
-            echo "::set-output name=status::fail" # Set a custom output named 'status' to 'fail'
-            exit 1  # Exiting with a non-zero status to indicate failure
+            echo "job-status=${{ steps.get_custom_job_1_status.outputs.job-status }}" >> $GITHUB_ENV
           fi
 
-      - name: Show Status Badge
-        if: ${{ always() && steps.custom_step_1.outputs.status == 'pass' }}
-        run: |
-          echo "Status: Pass"
-          # Add code here to display a badge for passing status
+  custom_job_2:
+    runs-on: ubuntu-latest
+    needs: [ custom_job_1 ]
+    if: ${{ always() && contains(needs.custom_job_1.result, 'failure') }}
 
-      - name: Show Else Message
-        env:
-          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
-        if: ${{ always() && steps.custom_step_1.outputs.status == 'fail' }}
-        run: |
-          echo "Else Message: Status not equal to 1"
-          echo "::set-env name=CUSTOM_STATUS::pass" # Set a custom environment variable named 'CUSTOM_STATUS' to 'pass'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Generate Badge
-        if: always() # This step will always run, regardless of previous steps
+      - name: Your Custom Step 2
         run: |
-          status=${{ steps.custom_step_1.outputs.status }}
-          if [ "$status" != "pass" ]; then
-            # Generate and display a badge for passing status
-            echo "![Pass](https://img.shields.io/badge/Status-Pass-brightgreen)"
-          else
-            # Generate and display a badge for the else case
-            echo "![Else](https://img.shields.io/badge/Status-Else-red)"
-          fi
+          # Your custom script or command here
+          # Example:
+          echo "Running Custom Job 2 even if Custom Job 1 failed jobs.custom_job_1"
