testt

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -32,9 +32,17 @@ jobs:
           echo "::set-output name=status::${var}"
 
       - name: Show Status Badge
-        if: steps.custom_step_1.outputs.status == '1'
+        if: steps.custom_step_1.outputs.status == 1
         run: |
-          echo "Status: Pass"
+          echo "Status: Pass $var"
+          if [ "$var" == 1 ]; then
+            # Increment the variable by +1
+            var=$((var+1))
+            echo "var is equal to 1"
+          else
+            echo "var is not equal to 1, failing the job"
+            exit 1  # Exiting with a non-zero status to indicate failure
+          fi
           # Add code here to display a badge for passing status
 
       - name: Show Else Message
